# Generated by Django 5.1 on 2024-08-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_order_taxprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='postalCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shippingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
