# Generated by Django 5.1 on 2024-08-31 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_shippingaddress_postal_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
