# Generated by Django 5.1 on 2024-08-31 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_product_main_image_alter_product_model_3d_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='texture',
        ),
    ]
