# Generated by Django 5.1 on 2024-08-31 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_product_main_image_alter_product_model_3d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='product',
            name='sec_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
