# Generated by Django 5.1 on 2024-09-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_3d',
            field=models.FileField(blank=True, default='/placeholder.png', null=True, upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, default='/placeholder.png', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='product_images/'),
        ),
    ]
